### ISSUE TITLE
Minor patches: NFE

### ISSUE THREAD

**Issue by SebastianThomas** [SebastianThomas/minesweeper#16]
Check if a minor patch version is given or not. If it is, separate before the "." (dot), otherwise before the "-". 

```
Exception in thread "Thread-1" java.lang.NumberFormatException: For input string: "8.1"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
        at java.base/java.lang.Integer.parseInt(Integer.java:652)
        at java.base/java.lang.Integer.parseInt(Integer.java:770)
        at de.sth.minesweeper.updates.Update.getReleaseMinorVersion(Update.java:95)
        at de.sth.minesweeper.updates.Update.getUpdateOptions(Update.java:73)
        at de.sth.minesweeper.updates.UpdatePanel.lambda$new$0(UpdatePanel.java:39)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by SebastianThomas** [comment]
Fixed with v4.8.2-ea
